name: Ontwikkel

on: [push, pull_request]

jobs:
    laravel-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                php-version: '7.4'
                extension-csv: intl, gd, zip, bcmath

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Install Dependencies
              run: composer install --prefer-dist

            - name: Copy .env
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"
            - name: Generate key
              run: php artisan key:generate
            - name: Execute tests (Unit and Feature tests) via PHPUnit
              run: composer test
            - name: ZAP Scan
              uses: zaproxy/action-full-scan@v0.1.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                docker_name: 'owasp/zap2docker-weekly'
                target: 'https://127.0.0.1/'
#                rules_file_name: '.zap/rules.tsv'
                cmd_options: '-a
# nbhjmghjjghghjghjghj
