name: Ontwikkel

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
              
            - name: Use example environment variables
              run: cd /home/runner/work/StraatDev/StraatDev/ && mv .env.example .env && sed -i 's/APP_ENV=local/APP_ENV=production/g' .env && sed -i 's/APP_DEBUG=true/APP_DEBUG=false/g' .env
              
            - name: Build the docker-compose stack
              run: docker-compose up -d
              
            - name: Wait 15 seconds
              uses: jakejarvis/wait-action@master
              with:
                time: '15s'
                
            - name: Check running containers
              run: docker-compose ps
              
            - name: Populate DB
              run: docker-compose exec php artisan migrate:refresh --seed --force
              env:
                COMPOSE_INTERACTIVE_NO_CLI=1
              
            - name: Generate APP_KEY
              run: docker-compose exec php artisan key:generate --force
              env:
                COMPOSE_INTERACTIVE_NO_CLI=1
