name: Ontwikkel

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
              
            - name: Use example environment variables
              run: mv .env.example .env
              
            - name: Build the PHP container
              run: docker-compose build php && docker-compose run php composer install 
              
            - name: Build the docker-compose stack
              run: docker-compose up -d
              
            - name: Wait 15 seconds
              uses: jakejarvis/wait-action@master
              with:
                time: '15s'
                
            - name: Check running containers
              run: docker-compose ps
              
            - name: Populate DB
              run: docker-compose exec -T php artisan migrate:refresh --seed --force
              
            - name: Generate APP_KEY
              run: docker-compose exec -T php artisan key:generate --force
